{
 "title": "UD20 - Catalogo prodotti - FE/BE metrics",
 "tags": [
  "academy-observability",
  "ud20",
  "products"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Target UP frontend/backend",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 7 },
   "targets": [
    {
     "expr": "up{job=~\"products-.*\"}",
     "legendFormat": "{{service}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Request rate per path",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 16, "h": 7 },
   "targets": [
    {
     "expr": "sum by (service,path,status) (rate(app_http_requests_total{path=~\"/|/products.*|/ready\"}[1m]))",
     "legendFormat": "{{service}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Error rate 5xx",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 7, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (service,path,status) (rate(app_http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "{{service}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Latency p95 products",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 7, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, service, path) (rate(app_http_request_duration_seconds_bucket{path=~\"/|/products.*\"}[5m])))",
     "legendFormat": "{{service}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Average latency seconds",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 15, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (service,path) (rate(app_http_request_duration_seconds_sum{path=~\"/|/products.*\"}[5m])) / sum by (service,path) (rate(app_http_request_duration_seconds_count{path=~\"/|/products.*\"}[5m]))",
     "legendFormat": "{{service}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Total requests by service/path/status",
   "type": "table",
   "gridPos": { "x": 12, "y": 15, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (service,path,status) (app_http_requests_total)",
     "legendFormat": "{{service}} {{path}} {{status}}"
    }
   ]
  }
 ]
}